<?php
return array (
  'site-title-mn' => 'Амин хариуцлага',
  'site-title-en' => 'UBeSafe',
  'site-description-mn' => 'Амин хариуцлага',
  'site-description-en' => 'UBeSafe',
  'site-keywords' => 'Амин хариуцлага, АминХариуцлага, UBeSafe',
  'site-social-share' => 'http://ckbank1.ckbank.mn/files/site_meta/808d2b3e190e75668221672de0eb7064.jpg',
  'contact-email' => 'ubesafe@gmail.com',
  'contact-phone' => '91177722',
  'facebook' => 'https://www.facebook.com/UBeSAFE/',
  'youtube' => 'https://www.youtube.com/channel/UC9mUnZCn8l8N2ZHIXWpiSOg',
  'contact-address-mn' => '',
  'contact-address-en' => '',
  'twitter' => 'https://twitter.com/UBeSAFE1?lang=en',
  'facebook-id' => 'ubeSafe',
  'site-analytics-script' => '',
  'donate-link' => 'https://docs.google.com/forms/d/1_uPZndBk0hiT-zS2Dp4MOIDKqUQ1AEProvMAmxf4p6g/edit?usp=sharing',
  'request-link' => 'https://docs.google.com/forms/d/1pkk0GCzZIWKaCuHkkGeI2AbCZjUNocsHjFx9vrpCf3o/edit?usp=sharing',
  'youtube-video-link' => 'https://www.youtube.com/embed/z6tkoZPpu70',
  'request-receiver-email' => 'globalshapersub@gmail.com',
);